
CREATE TABLE locations(
    venue VARCHAR(150) NOT NULL PRIMARY KEY,
    zipcode VARCHAR (10) NOT NULL,
    lat DECIMAL(9,6) NOT NULL,
    long DECIMAL(9,6) NOT NULL,
)


CREATE TABLE traffic_events(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    start_date DATETIME NOT NULL,
    short_name VARCHAR(250) NOT NULL,
    status_value VARCHAR(50) NOT NULL,
    status_complete BOOLEAN NOT NULL,
    venue VARCHAR (150) NOT NULL
        REFERENCES locations ON DELETE CASCADE
)

